# Generated by Django 5.1.6 on 2025-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="Ikeja", max_length=256),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="Nigeria", max_length=256),
        ),
        migrations.DeleteModel(
            name="UserAddress",
        ),
    ]
