# Generated by Django 5.1.6 on 2025-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_city_user_country_delete_useraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=256),
        ),
    ]
