# Generated by Django 5.1.6 on 2025-03-06 13:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverificationotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
