# Generated by Django 5.1.6 on 2025-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_country_code_alter_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="national_id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
