# Generated by Django 5.1.6 on 2025-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_profile_private_key_profile_wallet_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deposit_mail_sent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet_activated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="private_key",
            field=models.CharField(
                blank=True, db_column="private_key", max_length=500, null=True
            ),
        ),
    ]
