# Generated by Django 5.1.6 on 2025-04-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0009_profile_deposit_mail_sent_profile_wallet_activated_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="deposit_mail_sent",
        ),
    ]
