# Generated by Django 5.1.6 on 2025-03-19 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CryptoDeposit",
        ),
    ]
