# Generated by Django 5.1.6 on 2025-04-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_delete_cryptodeposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, null=True),
        ),
    ]
