# Generated by Django 5.1.6 on 2025-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_transaction_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="deposit_mail_sent",
            field=models.BooleanField(default=False),
        ),
    ]
