# Generated by Django 5.1.6 on 2025-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plan_duration",
                    models.IntegerField(
                        choices=[
                            (15, "10% for 15 days"),
                            (30, "20% for 30 days"),
                            (60, "45% for 60 days"),
                            (90, "70% for 90 days"),
                            (180, "150% for 180 days"),
                            (365, "300% for 365 days"),
                            (730, "600% for 730 days"),
                        ]
                    ),
                ),
                (
                    "expected_return",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("matured_at", models.DateTimeField()),
                ("is_processed", models.BooleanField(default=False)),
            ],
        ),
    ]
